from userbot.database import Database
db = Database()
db.connect("x.sql")
db.create_table("snip", "trigger TEXT, message_id INT")
db.create_table("filter", "trigger TEXT, message_id INT")
db.create_table("gban", "from_user_id TEXT, chat_id TEXT, reason TEXT")
db.create_table("gmute", "from_user_id TEXT, chat_id TEXT, reason TEXT")
db.create_table("afk", "is_afk INT")
db.create_table("pmpermit", "user_id TEXT, is_approved INT")
print(db.db2json())
