services:
  - type: web
    plan: free
    name: XUserBot
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m userbot
    repo: https://github.com/LavanderProjects/XUserBot
    branch: master
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false

    autoDeploy: false
